// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VinylPi.DataAccess;

#nullable disable

namespace VinylPi.DataAccess.Migrations
{
    [DbContext(typeof(VinylDbContext))]
    [Migration("20230130014753_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Artist", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Anv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BasicInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Join")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicInformationId");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.BasicInformation", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Cover_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Master_id")
                        .HasColumnType("int");

                    b.Property<string>("Master_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BasicInformation", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Descriptions", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BasicInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicInformationId");

                    b.ToTable("Formats", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Genres", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BasicInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicInformationId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BasicInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Catno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity_type_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicInformationId");

                    b.ToTable("Labels", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Pagination", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("Items")
                        .HasColumnType("int");

                    b.Property<int?>("Pages")
                        .HasColumnType("int");

                    b.Property<int?>("Per_page")
                        .HasColumnType("int");

                    b.Property<int?>("UrlsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrlsId");

                    b.ToTable("Pagination", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Release", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("Date_added")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Instance_id")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.Property<int?>("basic_informationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.HasIndex("basic_informationId");

                    b.ToTable("Releases", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PaginationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaginationId");

                    b.ToTable("Root", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Styles", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BasicInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BasicInformationId");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Urls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Last")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Next")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Urls", (string)null);
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Artist", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.BasicInformation", null)
                        .WithMany("Artists")
                        .HasForeignKey("BasicInformationId");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Descriptions", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.Format", null)
                        .WithMany("Descriptions")
                        .HasForeignKey("FormatId");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Format", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.BasicInformation", null)
                        .WithMany("Formats")
                        .HasForeignKey("BasicInformationId");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Genres", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.BasicInformation", null)
                        .WithMany("Genres")
                        .HasForeignKey("BasicInformationId");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Label", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.BasicInformation", null)
                        .WithMany("Labels")
                        .HasForeignKey("BasicInformationId");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Pagination", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.Urls", "Urls")
                        .WithMany()
                        .HasForeignKey("UrlsId");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Release", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.Root", null)
                        .WithMany("Releases")
                        .HasForeignKey("RootId");

                    b.HasOne("VinylPi.DataAccess.Models.Collection.BasicInformation", "basic_information")
                        .WithMany()
                        .HasForeignKey("basic_informationId");

                    b.Navigation("basic_information");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Root", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.Pagination", "Pagination")
                        .WithMany()
                        .HasForeignKey("PaginationId");

                    b.Navigation("Pagination");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Styles", b =>
                {
                    b.HasOne("VinylPi.DataAccess.Models.Collection.BasicInformation", null)
                        .WithMany("Styles")
                        .HasForeignKey("BasicInformationId");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.BasicInformation", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Formats");

                    b.Navigation("Genres");

                    b.Navigation("Labels");

                    b.Navigation("Styles");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Format", b =>
                {
                    b.Navigation("Descriptions");
                });

            modelBuilder.Entity("VinylPi.DataAccess.Models.Collection.Root", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
